name = "TestPlotlyJS"
uuid = "7498b32a-fcec-4368-b918-411a4642cb4f"
authors = ["Boris Orostica Navarrete"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
